### PR TITLE
Handle missing artwork for Tidal

### PR DESCRIPTION
**Pull request by monkeypox**
This handles missing artwork for tidal sourced tracks, a new 150x150 png8 image is included for lists rather than using the normal svg.

This also:

1) enables thumbs for mobile and adjusts the spacing a little.
2) adds a speaker icon instead of the queue number for the currently playing track.
3) updates the btnbarfix routine a bit to provide better contrast for the textvariant color

### CODE REVIEW

**Comment by moodeaudio** [comment]
Theres couple of conflicts :-0

Did you want the small thumbs for lists to be 150x150 or 50x50? 
I modified thumbcache to output filename_sm.jpg at 50x50 but can change that.

**Comment by moodeaudio** [comment]
I think I might have messed up the PR by trying to resolve the conflict by deleting the .min file but I was able to successfully merged it, fix things up and push the commit. 

It didn't automatically show it as merged though in the repo so I'm manually closing it.

**Comment by monkeypox** [comment]
Weird, I didn’t intentionally include a .min file and only checkmark relevant files for the pr. Maybe it got added accidentally when i rebased to deal with the playerlib.js and moode.css conflicts?

Looking at the code I think it just ended up ignoring the conflict code so it’s missing fixed artwork for the playbar and some spacing changes from moode.css. 😩

**Comment by moodeaudio** [comment]
Oh man :-0

No need to post another PR if the missing changes aren't too complex. Just email me the code snippets like in the old days, lol.

Anyway I sent you an email about another issue.

**Pull request closed without merging**
