### PR TITLE
load available mpd version from config file

### PR DESCRIPTION
**Pull request by bitkeeper**
Matches issue #141 Load available mpd versions from config file.

### CODE REVIEW

**Comment by moodeaudio** [comment]
Not sure what happened but the PR merge went OK in GitHub desktop but its still showing in this repo as an open PR.

If I can't figure it out on my end I'll just close this manually.

**Comment by moodeaudio** [comment]
Note that this PR was merged in Github Desktop but was still showing as Open in this repo after pushing the commit. Resolution is to acknowledge acceptance of the PR but close manually,

**Comment by bitkeeper** [comment]
@moodeaudio To prevent multiple commits I added the rename of config file to the previous commit, maybe that caused the strange behaviour ?

**Comment by moodeaudio** [comment]
It could have been a timing issue related to when I merged the PR vs when you added the rename.

Here's a pic of the Git Desktop history.

Screen Shot 2020-06-28 at 10 31 48 AM

**Pull request closed without merging**
