### PR TITLE
Analog clock initial commit

### PR DESCRIPTION
**Pull request by AlbertoNarduzzi**
See initialization and/or code for available parametrisation.

### CODE REVIEW

**Comment by moodeaudio** [comment]
Thus is cool idea. Can you attach a screen shot?

It's prolly going to have some conflicts after the CSS refactoring changes are committed in a few weeks but that can be worked out afterwords.

**Comment by AlbertoNarduzzi** [comment]
Did you receive my mail about cosmetics? think of the original as with just
plain hands... though I do prefer this one.
P.S. the PR already includes the option in preferences to chose from Cover
/ Digital clock / Analog clock...

**Comment by moodeaudio** [comment]
I'll check it out a bit later.

**Comment by moodeaudio** [comment]
Oops. This one has some commits that are "out-of-scope"

Resubmit just the analog clock!

**Comment by AlbertoNarduzzi** [comment]
Yeah,

I just saw it now that I was testing it on the 7''...
I'll fix it and create a new PR.

**Comment by AlbertoNarduzzi** [comment]
Hi Tim,

ok, now it's clean.

Cheers, Al.

**Pull request closed without merging**
