### PR TITLE
[WIP] Basic MQTT API implementation to monitor and control moode using the MQTT protocol

### PR DESCRIPTION
**Pull request by dotWee**
> **Note:** currently in very early development!

This pull request adds basic control mechanisms to monitor and control moode using the [MQTT](https://mqtt.org) protocol.

#### UI related notes:

- A MQTT broker has to be defined on the sys-config (commits 0d6fa34, 04603df & 0a59063)

#### Things to do:

- [ ] Look for the most platform compatible MQTT client
- [ ] Gather possible controllable player actions, other than _volume_ & _play_/_pause_
- [ ] Maybe allow logs to be published using MQTT

### CODE REVIEW

**Comment by moodeaudio** [comment]
Interesting PR. Some questions below.

What are the usage scenarios?
What types of clients would be used to control moOde via MQTT?

**Comment by dotWee** [comment]
> What are the usage scenarios?

The beauty of an MQTT API opens up many potential use cases primary related to the _Smart Home_ / _Home Automation_ category as another IoT device.

Some good articles regarding the role of MQTT in _Smart Home_ / _Home Automation_:

- [A Brief Understanding of the Role of MQTT Protocol in IoT](https://beyondroot.com/blog/a-brief-understanding-of-the-role-of-mqtt-protocol-in-iot/)
- [Smart Homes and MQTT](https://stevessmarthomeguide.com/smart-homes-mqtt/)
- [Home Audomation With MQTT and Home Assistant](https://medium.com/swlh/home-automation-with-mqtt-and-home-assistant-techtalk-gist-734bc89b5e53)

> What types of clients would be used to control moOde via MQTT?

Any other MQTT client or MQTT integrated device. 

Lets say a moOde instance subscribes to the topic `moodeplayer/cmd/vol` (`moodeplayer` as the device, `cmd` short for command, `vol` short for volume).

Now whenever another MQTT client wants to change moOde's audio current volume, it publishes the payload `70` (`70` for audio volume 70%) to the topic `moodeplayer/cmd/volume`.

Another more detailed usage scenario would be the integration into Apple's HomeKit using [homebridge](https://homebridge.io) & [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing) as an [audio device](https://www.homekithelper.net/devices/audio). This would allow moOde to be easily controlled by any other iOS device within the native Home application.

**Comment by moodeaudio** [comment]
For sure those are valid use cases but my concern is the amount and complexity of code that would need to be added to support functions beyond basic play/pause/next/prev/vol.

I suppose we need to see what the list looks like from your TODO:
Gather possible controllable player actions, other than volume & play/pause

And admittedly I'm not knowledgable at this point regarding MQTT so lets keep working on this PR until it gets to a point where it can be merged for testing. I'll try to get up to speed.

**Comment by bitkeeper** [comment]
Interesting. Also some questions:

- Are you planning a deep integration into moOde?
- Or use one of the many already available mqtt mpd bridge?

**Comment by TheOldPresbyope** [comment]
What goes around, comes around. MQTT last mentioned in Forum 18 months ago. We didn't decide then on a basic message set, the original proponent disappeared, and the subject died.

This should be fun.

**Comment by dotWee** [comment]
> For sure those are valid use cases but my concern is the amount and complexity of code that would need to be added to support functions beyond basic play/pause/next/prev/vol.
> 
> 
> 
> I suppose we need to see what the list looks like from your TODO:
> 
> Gather possible controllable player actions, other than volume & play/pause
> 
> 
> 
> And admittedly I'm not knowledgable at this point regarding MQTT so lets keep working on this PR until it gets to a point where it can be merged for testing. I'll try to get up to speed.

I'm still working my way through the source code (with only very basic PHP knowledge).

Currently I'm planing to rely on MPD's commands list like the currently implemented [Command API](https://github.com/moode-player/moode/blob/e6f6f8daed5c90bb65d029ea6b06de2215fd3343/www/setup.txt#L215).

**Comment by moodeaudio** [comment]
Also the availability of MPD bridges kind of makes the need for directly embedding MQTT API into moOde unnecessary.

Let's close this. It can be reopened if direct MQTT embedding becomes needed.

**Comment by dotWee** [comment]
> - Are you planning a deep integration into moOde?
> - Or use one of the many already available mqtt mpd bridge?

Didn't know about already available MDP MQTT bridges! 

Will use those as a basic starting point, a deeper integration into moOde is worth a thought once basic functionality is integrated successfully.

**Pull request closed without merging**
