### PR TITLE
Make compilation artists show up in tag view and find their songs.

### PR DESCRIPTION
**Pull request by scripple**
On develop but untested.  Seems like it should work though.

### CODE REVIEW

**Comment by moodeaudio** [comment]
Much appreciated.

I'll try to test in the next few days.

**Comment by scripple** [comment]
Ok, I wanted this to be separate, but I'm not very familiar with git/github.  So added to this all artist change is now 4 lines in commit ea0bd43 that will fix the janky scrolling of album view caused by your lazy image loading.   Letters now go the right place when you click them too as opposed to click get close, click get closer, etc.

If you like it the styling can be moved into your css files instead of inline.

Sorry the two changes got merged.  :(

**Comment by moodeaudio** [comment]
The place holder issue in native lazy view has been addressed by the PR below. Thanks for raising the issue :-)
https://github.com/moode-player/moode/pull/191

The code changes that result in compilation artists showing in the Artist list along with their tracks breaks album grouping that uses the Album Artist tag and we lose the convenience of tapping "Various Artists" to show a list of all the compilation albums. 

The attached screen shots show how a compilation album would appear.

But given that the code changes are minimal there could be a Library option to let the user choose how they want to handle artists and compilations.  What do you think?

Screen Shot 2020-09-20 at 4 23 40 PM
Screen Shot 2020-09-20 at 4 23 52 PM

**Comment by scripple** [comment]
Re: Lazy load, as long as it works that's all that matters to me.

On the artists something must have changed for the worse with this mod from 6.X to 7.X.  I do see artists split out like your Wynton Kelly Trio but if I were to click on any of the Wynton entries the one album would show and all the tracks on that album show.  Also I do have "Various Artists" in my artist list and when I click it all my compilation albums show in the album list and clicking on any one of them brings up all the tracks for that album.

I wonder if this has do with your musicbrain or whatever it's called addition to the album tag preventing it from correctly connecting everything.

**Comment by scripple** [comment]
I'm ok with a switch, but if there's a 7.x image I can write to an SD card I could try to poke at making it better.

**Comment by moodeaudio** [comment]
Can never rule out bugs or unintended side-effects. I'll add you to the Test Team group in the Forum. This is where the beta image downloads are posted and we try to debug and improve the code before release. Theres no timing yet for releasing 7 so plenty of room to find and fix bugs :-)

Are you @seashell in the Forum?

**Comment by scripple** [comment]
Sounds good.  Yes I'm @seashell on the forum.

**Comment by moodeaudio** [comment]
Your Forum ID was added to the Test Team group. That Forum section should now be visible to you. Look for the moOde 7 test releases thread.

**Comment by scripple** [comment]
I see it.  I'll take a look when you post the next beta image.

**Comment by scripple** [comment]
A quick question, I noticed at the top of your image you have "Wes Montgomery & The Wynton Kelly Trio", as opposed to "Wynton Kelly Trio & Wes Montgomery" that is highlighted.  What is your actual Album Artist tag for this album?

**Comment by moodeaudio** [comment]
They are two different albums.

Screen Shot 2020-09-21 at 1 38 19 PM
Screen Shot 2020-09-21 at 1 38 30 PM
Screen Shot 2020-09-21 at 1 38 52 PM
Screen Shot 2020-09-21 at 1 39 14 PM

**Comment by scripple** [comment]
Just to be clear, before my mod "Wynton Kelly Trio" and "Wynton Kelly Trio & Wes Montgomery" don't show up in your artist list at all right?  Because that album only shows up under "Various Artists".

I know why I have "Various Artists" and you don't.  I believe it's really easy to make sure all the old listings are there and just new ones are added.

If I'm right about those two artists not showing up before my mod I also know why your tracks are split and mine aren't.   But it would be probably impossible to fix because it's very tag specific.

So if your compilation albums all showed up under "Various Artists" as before *AND* you have the new entries that are split is that ok?  (Basically the new splits are just more specific).

**Comment by moodeaudio** [comment]
```
"Just to be clear, before my mod "Wynton Kelly Trio" and "Wynton Kelly Trio & Wes Montgomery" don't show up in your artist list at all right? Because that album only shows up under "Various Artists"."
```
Correct. Because the code prefers grouping by Album Artist and that tag is set to "Various Artists" in my compilation albums.

Compilation albums have always been a challenge cos there is no standard tag to identify them. The current approach that we use in moOde which is to group by Album Artist has so far worked well for most of our users, and the code seems to be very eficient.

I'm not sure whats best going forward.

Years ago the code grouped by Artist like your mods and there was a separate routine that scanned through all the tracks to try and determine the compilation albums and form a separate group. This group had to be specifically handled in renderArtists and renderAlbums and the whole process  was inefficient for larger collections.

```
So if your compilation albums all showed up under "Various Artists" as before AND you have the new entries that are split is that ok?
```

Yes that would prolly be best of both worlds :-)

**Comment by scripple** [comment]
Then the best of both worlds it pretty easy.  Basically the reason it worked for me is I have some tracks whose Artist and Album Artist are both "Various Artist" which gave me the Various Artist entry.  Clicking on that "Various Artist" provides the behavior you have now.

So I made reduceArtists add entries for the Artist and the Album Artist if it exists and is different from artist.  This of course collects the "compilation tag" whatever it is and every other entry you possibly had before.  

The other option, and I like this less and haven't tried it, is rather than check artist and album artist at reduce we could have a special case of add the compilation tag but that would have to check that said person actually has albums with the compilation tag and have extra logic outside reduce artists.

I'll have to clean it up but I can push this back enclosed in the TEST comments if you like option one above.

**Comment by scripple** [comment]
I went ahead and pushed the changes.  I just defined a new reduceArtists in a comment block and removed the two one line //TEST comments in the old reduce artists.  

Uncomment all the // TEST stuff and comment out the original reduceArtists to test.

**Comment by moodeaudio** [comment]
```
I have some tracks whose Artist and Album Artist are both "Various Artist" which gave me the Various Artist entry. Clicking on that "Various Artist" provides the behavior you have now.
```

If both tags contain the string "Various Artists" which tag contains the actual artists's name?

**Comment by scripple** [comment]
It's a generic sampler CD that businesses used to hand out.  It has no artist information and wasn't in the CD DB of the time when I scanned it.

**Comment by moodeaudio** [comment]
Tested and here are results:

- OK: All artists are listed including those in compilation albums
- OK: The artist "Various Artists" is listed and clicking it displays the list of all compilation albums (Album Artist = "Various Artists")
- NOT OK: Clicking any artist that was broken out from compilations does not list its albums or tracks.

Please confirm I have the correct // TEST: code blocks. I've listed them below.

```
## CODE BLOCK 1
// TEST:
// This replaces the entire original reduceArtists
function reduceArtists(acc, track) {
	if (track.artist) {
		var artist = (track.artist).toLowerCase();
		if (!acc[artist]) {
			acc[artist] = [];
			acc[artist].artist = track.artist;
		}
		acc[artist].push(track);
	} else {
		// track.artist not set, define artist for comparison below
		var artist = null;
	}
	if (track.album_artist) {
		var album_artist = (track.album_artist).toLowerCase();
		if (album_artist != artist) {
			if (!acc[album_artist]) {
				acc[album_artist] = [];
				acc[album_artist].artist = track.album_artist;
			}
			acc[album_artist].push(track);
		}
	}
	return acc;
}
// TEST:

## CODE BLOCK 2
function filterArtists() {
	// Filter artists by genre
	var songsfilteredByGenre = allSongs;
	if (LIB.filters.genres.length) {
		songsfilteredByGenre = songsfilteredByGenre.filter(filterByGenre);
	}
	filteredArtists = Object.values(songsfilteredByGenre.reduce(reduceArtists, {})).map(function(group){ return group.artist; });
    // TEST:
    // Natural ordering
	try {
		var collator = new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'});
        filteredArtists.sort(function(a, b) {
            return collator.compare(removeArticles(a).toLowerCase(), removeArticles(b).toLowerCase());
        });
    }
    // Fallback to Default ordering
    catch (e) {
        filteredArtists.sort(function(a, b) {
             a = removeArticles(a).toLowerCase();
             b = removeArticles(b).toLowerCase();
             return a > b ? 1 : (a < b ? -1 : 0);
        });
    }
    // TEST:
}

## CODE BLOCK 3
function filterAlbums() {
	filteredAlbums = allAlbums;
	filteredAlbumCovers = allAlbumCovers;

	// Filter by genre
	if (LIB.filters.genres.length) {
		filteredAlbums = filteredAlbums.filter(filterByAllGenres);
		filteredAlbumCovers = filteredAlbumCovers.filter(filterByAllGenres);
	}
	// Filter by artist
	if (LIB.filters.artists.length) {
		filteredAlbums = filteredAlbums.filter(filterByArtist);
		filteredAlbumCovers = filteredAlbumCovers.filter(filterByArtist);
        // TEST:
        var artistSongs = allSongs.filter(filterByArtist);
 		var songKeys = artistSongs.map(function(a) {return a.key;});
 		filteredAlbums = filteredAlbums.filter(function(item){return songKeys.includes(keyAlbum(item));});
 		filteredAlbumCovers = filteredAlbumCovers.filter(function(item){return songKeys.includes(keyAlbum(item));});
        // TEST:
	}
    // Filter by file last-updated timestamp
    if (LIB.recentlyAddedClicked) {

**Comment by scripple** [comment]
Two old lines need to be commented out in code block 3.  I put them between the big XXXXXXXXXXX lines below.


## CODE BLOCK 3
function filterAlbums() {
	filteredAlbums = allAlbums;
	filteredAlbumCovers = allAlbumCovers;

	// Filter by genre
	if (LIB.filters.genres.length) {
		filteredAlbums = filteredAlbums.filter(filterByAllGenres);
		filteredAlbumCovers = filteredAlbumCovers.filter(filterByAllGenres);
	}
	// Filter by artist
	if (LIB.filters.artists.length) {
// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX COMMENT THESE LINES  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
// They do the old filter and eliminate the new results before the new code see them.
//		filteredAlbums = filteredAlbums.filter(filterByArtist);
//		filteredAlbumCovers = filteredAlbumCovers.filter(filterByArtist);
// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX COMMENT THESE LINES XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        // TEST:
        var artistSongs = allSongs.filter(filterByArtist);
 		var songKeys = artistSongs.map(function(a) {return a.key;});
 		filteredAlbums = filteredAlbums.filter(function(item){return songKeys.includes(keyAlbum(item));});
 		filteredAlbumCovers = filteredAlbumCovers.filter(function(item){return songKeys.includes(keyAlbum(item));});
        // TEST:
	}
    // Filter by file last-updated timestamp
    if (LIB.recentlyAddedClicked) {

**Comment by moodeaudio** [comment]
That works :-)

It should prolly be the default of doing artists. I don't really see a need for a user option for this.

**Comment by scripple** [comment]
Cool.  Do you need me to do anything more with the PR?  Or should we close it?

**Comment by moodeaudio** [comment]
Might as well first get it in front of The Forum Test Team group. My experience with the Library is that you never can tell what might pop up after changing it cos user collections range from pristine to completely ghetto, moderate size to quarter million tracks :-0

**Comment by moodeaudio** [comment]
Changes added manually to develop branch for testing.

**Comment by scripple** [comment]
Agreed.  No need for this to stay open as it's effectively been merged.  Closing the request.

**Pull request closed without merging**
