### PR TITLE
Allow specifying Librespot zeroconf port

### PR DESCRIPTION
**Pull request by curiousCephalopod**
Implements #694 

Leaving as a draft as I'm unable to test it this moment, feel free to merge if you're happy it works.

### CODE REVIEW

**Comment by curiousCephalopod** [comment]
Librespot enabled with default settings, using a random port.
Screenshot 2024-12-07 204232
Screenshot 2024-12-07 204201

Librespot enabled with specified port.
Screenshot 2024-12-07 204254
Screenshot 2024-12-07 205904

**Comment by moodeaudio** [comment]
Sure no prob.

**Comment by moodeaudio** [comment]
Looks good to my eye. I'll go ahead and merge and report back after testing.

**Comment by moodeaudio** [comment]
No issues other than a minor fix to spo-config.php
https://github.com/moode-player/moode/commit/9525f793d09396e3c529c7e40aa7368e53cc430f

This will be part of upcoming 9.2.0 release for the year end. Many thanks :-)

**Pull request merged**
