### PR TITLE
Song lyrics

### PR DESCRIPTION
**Pull request by Stephanowicz**
**Search for lyrics of current playing song**

I had to create a new pull request as things got a bit messed up :D sorry...

Added a lyrics-query for the current playing song.  (You may also take a look [here](https://github.com/moode-player/moode/issues/280))
(Radio stations haven't been taken in consideration - maybe this needs additional steps.)

Requirements:

- Genius client access token
- php-dom (`sudo apt-get install php7.3-xml`)

The query is using the [genius.com api](https://docs.genius.com/#/getting-started-h1) - in order to use it You'll need to create a [free account](https://genius.com/signup_or_login). Then You need to [create a new api-client](https://genius.com/api-clients) in order to **generate a client access token**.
At moment, this token has to be put in the first line of the ./command/geniuslyrics.php file. 

The modal lyrics-window can be accessed by the playbar-menu.

Todo:

- An option to enter the token on the settings page (maybe with a small howto and a link for account creation and creation of api-clients).

image
image

 The title of the audio may differ a bit from the title in genius - In this case the query returns no result, but You can try again by changing the search string:

image

Cheers, Stephan

### CODE REVIEW

**Comment by moodeaudio** [comment]
Looking good :-) 

I'll plan to merge and test tomorrow.

**Comment by monkeypox** [comment]
Maybe this could automatically run when a song plays and we could additionally fetch cover art to sub in if it’s missing? If php makes the timing tricky there’s an mit licensed js library that does a similar thing:

https://github.com/farshed/genius-lyrics-api/blob/master/README.md

It looks like it returns a promise with the relevant data, in the .then() function moode could insert the lyrics data and check the current url to see if it’s the same as the default image and if so swap in the genius url.

**Comment by moodeaudio** [comment]
An auto-display option might be cool but there would need to be a way to display the lyrics w/o obscuring the whole UI with the modal.

**Comment by moodeaudio** [comment]
After reviewing the TOS and some posts in their Forum it appears that they do not allow 3rd party apps to display their lyrics unless they expressly grant a license to do so. 

Forum post by Nightpool https://genius.com/nightpool
https://genius.com/discussions/371251-Genius-based-lyrics-plugin-for-winamp
```
"Unfortunately, we don’t support allowing third parties to display our lyrics without licensing.
There are legal barriers that prevent us from allowing others to display our lyrics in third party apps."
```

This means that it will not be possible to include this PR unless something changes and there is a way to obtain an app license  or they provide a general license that allows FOSS apps to use their service. If either of these things happen I can reopen the PR.

**Comment by Stephanowicz** [comment]
Hmm :(

ok

**Comment by bitkeeper** [comment]
@Stephanowicz too bad about the licensing, it was a nice addition.

**Comment by moodeaudio** [comment]
I agree its a shame that we can't merge this nice contribution at this time but I never loose hope. Maybe someone should contact them and see whether there is an exception in their terms for FOSS (non commercial) applications that only need the capability for users too display the lyrics.

**Comment by Stephanowicz** [comment]
Thank you :)

well, at least I can enjoy it. xD

Honestly, I have not much hope that genius would agree to this, having in mind that post in their forum where on guy asked for integration in winamp...

So far, cheers. Stephan

**Comment by Stephanowicz** [comment]
Just came to my mind...how about displaying local stored lyrics if available? One could seperate the creation of the files from moode. So people may create them on their own or let  create  them by a script like we have here... so it's up to the user if he wants to use such a script independently from moode.

**Comment by moodeaudio** [comment]
Sure if the user modifies moOde code for their own purpose then there is no liability to the project. Maybe some sort of plugin system could be created.

**Comment by Stephanowicz** [comment]
how about offering options in the settings page - like 'local lyrics files' (maybe default setting) or 'external program'  (linking to a php script) ?

**Comment by moodeaudio** [comment]
That might be an option if there is a viable utility that users could use to easily batch create the local lyrics files otherwise it would be a huge burden to manually download lyrics file for each track :-0

**Comment by Stephanowicz** [comment]
Yes - well, as said before, the default action should be to check if there's a local lyrics file available. Otherwise, if the user has supplied a script, it will be called with the search params. The script will send back the lyrics to the ui. In addition the lyrics may be saved to a file either by the script or the ui.
So it's the liability of the user to supply a script that executes a lyrics query. 
But the process should be automated by the ui - so it's either an option that one can set in the settings or as alternative the ui may check a special folder for a script.
The interface would be as simple as possible - just artist and title as params and the plain lyrics in return.
I could imagine of an additional option to provide an own template for the script.

So the easiest option would be a special folder, e.g. "extensions/lyrics". This folder should contain a script which is able to perform a query independently - like php, perl or python. 
The interface would send artist and title as params and expects text in return.

**Comment by moodeaudio** [comment]
It's not likely that many users will be developing their own lyrics downloading script. A feature like this really needs a a structured plugin system that would allow a dev to create the feature in GitHub to be installed by user.

**Pull request closed without merging**
