### PR TITLE
Allow Timed display when MPD playing

### PR DESCRIPTION
**Pull request by fabitom**
In reference to issue #671

### CODE REVIEW

**Comment by moodeaudio** [comment]
We can't just delete the MPD test. It was added a long while back based on a lot of users not wanting CoverView to activate when something was playing.

This would have to be a new Prefs option but that involves a lot of moving parts and more code so I'm reluctant to consider it unless there was a sufficient demand for it.

What might be possible is to add a dev tweak, something like checking for the presence of a file in home dir. Something like the following:
`&& ($mpdState != 'play' || file_exists($_SESSION['home_dir'] . '/coverview_mpd_override') )`

**Comment by fabitom** [comment]
Sure, I understand. It mainly depends on the primary use of the streamer — whether it is meant for listening sessions, daily radio, or as an alarm clock ;). Is there already a mechanism in place that forces the overwriting of certain settings not available in the interface options, or would this be the first use?

**Comment by moodeaudio** [comment]
The php scripts would be overwritten during in-place update but the file in home dir would not. All you would need to do is make a sed patch that adds back the fie_exists() code.

**Comment by moodeaudio** [comment]
Will reopen if there is new information posted

**Comment by moodeaudio** [comment]
Update: 

I've added a Prefs option to control whether CoverView activates when MPD is playing.

Screenshot 2024-10-13 at 11 44 37 AM

**Comment by fabitom** [comment]
Nice, thanks!

**Pull request closed without merging**
