### PR TITLE
Move header.php from /var/local/www to /var/www.

### PR DESCRIPTION
**Pull request by bitkeeper**
Not any longer required to be in /var/local/www so move it to the place where the other sources are.

### CODE REVIEW

**Comment by moodeaudio** [comment]
If we ever decide to deliver /var/www as a squashfs, which was the case in an earlier moOde series, then we can't include header.php in that dir cos the <title> text (Browser title) gets updated.

**Comment by bitkeeper** [comment]
Maybe I am missing something, but can't we just fill in the title directly from $ _SESSION ?

Like:
```php
<title><?php echo $_SESSION['browsertitle']; ?></title>
```
Or is there important reason to change the code itself when the browser title is changed?

At least it works in my test environment and this construction will still work if you ever decide to use the squashfs again.
In that case no need to update the file and as benefit some code can be removed like the call to util.sh.

**Comment by moodeaudio** [comment]
That should work. I'll merge this and then make the changes to use the session var.

**Comment by bitkeeper** [comment]
@moodeaudio 

To be sure; also the sed command should be made comment in `command/util.sh` :

```php
	if [[ $2 = "browsertitle" ]]; then
		sed -i "s/<title>$3/<title>$4/" /var/local/www/header.php
	fi
```

Later on maybe some more cleaning todo, but that will take some more time.

**Comment by moodeaudio** [comment]
Yes, there's a few more locations where the SED needs to be commented out.

I push the commits a bit later.

**Pull request merged**
