### PR TITLE
Update README.md with developer info.

### PR DESCRIPTION
**Pull request by janiversen**
First PR, more to follow promptly.

Updated README, with some of the comments from the forum, and a couple of items I think was missing.

### CODE REVIEW

**Comment by moodeaudio** [comment]
Couple of things.

1. We definitely don't want to maintain a public TODO list. 
- The Forum already contains a thread for each upcoming release that provides WIP release notes describing whats included in the release and sometimes a note about what might be in the release.
- I maintain a personal check list to help me keep track of what I'm working on and this is what I refer to when I post in the Forum "Added to the TODO list".
- If you are looking for information on some TODO's with respect to the code base itself for example Refactoring, I'd suggest making a new Thread in the Forum and titled "Code base maintenance" or something like that.

2. For the readme.md page the challenge with adding to it is that 99% of the time this page is only viewed by people with GitHub accounts which means that they are most likely devs and so don't need any info on how to clone repos and make PR's.
- It would be helpful to add a "Troubleshooting and Support" heading with some text explaining that this is provided in the Forum (link to Support section) and not via Git issues which should only be used for development related stuff.
- Also helpful would be a link to the docs repo under the "Additional Resources" heading.

**Comment by janiversen** [comment]
The TODO is a matter of taste, and no problem. To me it is a convenient way of sharing information.

Actually a lot of new developers in projects needs hand holding to make the first steps. But please not I did not add "git clone" specifically, I added a section that contributions are welcome, and how does the projects wants bugs/enhancements to be handled.

I have worked quite long time mentoring newbies in projects like Libreoffice and organizations like Apache, so I think I know about about what people look for in a readme.

However it is your project, and you decide to merge or not.

**Comment by janiversen** [comment]
I added specifically "solve problems" (title can be changed) to tell how to get support in contrast to reporting a bug. I at least would never report a bug in a forum, nor would ask about support in a issue.

**Comment by janiversen** [comment]
Sorry for disturbing, I was honestly just trying to help, by bringing my experience to the table.

**Comment by moodeaudio** [comment]
There no problem with the PR and it's a helpful one. I'll update readme with some of the suggestions.
I suppose devs new to the project would need some "getting started" type info.

**Comment by janiversen** [comment]
Well your comments was quite different, it sounded a lot more like my PR was a burden, something I am very observant to, when starting in a new project.

I guess we view the project from different angles. As a newbie but with more project experience than most, I see a lot of issues, that are clear to the people who have been around a while.

I saw a possibility to combine developing the features I need and simultaneously help the project make a bigger step forward (by doing things the project need), mostly because I basically have all the time I want. When I engage in a project it is because there are mutual benefits, life is simply too short to fight an uphill battle.


This is open source so feel free to use what I suggested.

**Comment by moodeaudio** [comment]
No burden at all and the help is most welcome.
I prefer to get my perspectives on the table to stimulate a meaningful discussion. They are not by any means set in stone.
Often the proposals in PR's that are focussed on content/style rather than bug fixes take a lot more more time to consider.

**Pull request closed without merging**
