### PR TITLE
Appearance option: Show covers in Tag view: Yes/No

### PR DESCRIPTION
**Pull request by gbh-uk**
Adds an option in the Appearance configuration panel to show/hide album cover thumbnails in Album column of the Tag View.  I believe this is one of the 'Issues' you were looking to implement Tim.

Requires entry in db table cfg_system "tagviewcovers" default: Yes

### CODE REVIEW

**Comment by moodeaudio** [comment]
Hi Gary,

There are some conflicts prolly due to the updated version of playerlib.js that I committed earlier today as part of the work I'm doing to migrate the Library options from PHP to JS in the Appearance dialog. I first had to straighten out a few things in playerlib.

 No worries though because it's easy for me to add this feature manually. I'll just cut/paste from the PR :-)

-Tim

**Comment by moodeaudio** [comment]
The tagview covers feature has been committed.

After I finish migrating the lib options from php to the appearance dialog I'll cut an r650 test image  and mail out a download link.

There are a few more features planned for r650 including swizzles UI enhancements,  the Radio Manager from @duracell80 and some TODO list items.

**Comment by gbh-uk** [comment]
Great, thanks Tim.

I also finished working on appearance options for limiting the length of the Album and Artist labels in the Album view, however, as you mentioned, the core js files have changed so radically today that I think perhaps it may be better to hold off pushing it until r650. What do you think?

**Comment by duracell80** [comment]
I did spot an issue with community radio browser returned data in rb-populate.py in my radio stuff and committed to master in my repro. Should I do a new PR with that update?

**Comment by moodeaudio** [comment]
@gbh-uk I've got the ellipsis limited lines option covered :-)

I still need to slog through migrating the Lib options to Appearance. I've got half of them done and am procrastinating on the rest, lol.

**Comment by moodeaudio** [comment]
I'll close this PR now since the feature has been committed.

**Pull request closed without merging**
