### PR TITLE
Adding PR For Radio Manager

### PR DESCRIPTION
**Pull request by duracell80**
In the /var/www/radio directory is an install.sh file with some permissions changes I found needed for the functionality to work correctly. The json files should be made writable for sure. The manager includes an API lookup python script to the Community Radio Browser. There are also some utilities to manage u and s stations in Moode with the ability for users to bulk add stations and bulk change station logos as well as export/import a user stations zip file from the SDCARD directory. Finally in /var/www/radio/index.php are some API commands, one of which will stream a radio URL from a text input box and allow users to add shortcuts to play stations via URL.

### CODE REVIEW

**Comment by moodeaudio** [comment]
Thanks Lee. I'll review in the coming days.

**Comment by duracell80** [comment]
Thank you Tim, have a good day.

**Comment by moodeaudio** [comment]
Please provide a description of what this feature does and what type of structural changes it makes. There are a lot of files (23) and I'm not really sure how to begin reviewing them.

Does it preserve the built-in Radio Station feature?

**Comment by duracell80** [comment]
Yes preserves and builds on built in radio station feature.

Try this in a fresh 6.4.2 to get a feel for the enhancements.

$ cd /home/pi
$ git clone https://github.com/duracell80/MoodeRadio-Get.git
$ cd MoodeRadio-Get/scripts/make-radio-manager/

$ sudo chmod 755 install.sh
$ ./install.sh

Then load up moode/rdo-config.php and moode/rdo-config-rb.php

**Comment by moodeaudio** [comment]
Your contrib is prolly really good but I don't know what u expect me to do with this
"Try this in a fresh 6.4.2 to get a feel for the enhancements."

**Comment by duracell80** [comment]
Oh I gotcha. Yeah that install.sh will let you test drive everything on a new sdcard without doing the pull request, just SSH in and run those lines.

**Comment by moodeaudio** [comment]
This is not really a PR.

**Comment by duracell80** [comment]
Not sure I understand. The PR would add this capability to the project?

**Comment by moodeaudio** [comment]
The issue for me is that the PR is incomplete. I have no clue what to do after install.sh in order to test and validate that the feature is working properly.

Just provide steps to test and validate the functionality and we should be good to go.

**Comment by duracell80** [comment]
Ah I see. Let me work on detailed tests.

The easiest thing to do after setting all the permissions in Chrome desktop browser is to go to http://moode/ then use the configure > library and there should be two new buttons "Radio Browser" and "Radio Options".

These two buttons live in http://moode/lib-config.php.

Or as above you go to http://moode/rdo-config.php and http://moode/rdo-config-rb.php in a Chrome desktop browser. That's really how you access the UI and go from there.

**Comment by moodeaudio** [comment]
Cool, thx :-)

**Comment by duracell80** [comment]
This is something you won't understand by looking at code, it's a management UI for stations that in part uses an external service to generate playlists of user submitted URL's to a community service.

Community Radio Browser ...
https://www.youtube.com/watch?v=yRxKWwLS-zM

It also adds highly needed and multiple requested features from Moode users because managing stations is very difficult. Bulk delete of u stations I didn't have time to look at yet.

rdo-config.php ...
https://www.youtube.com/watch?v=vimwPJKpz6w

**Comment by moodeaudio** [comment]
Hi Lee,

I will try to test tonight.

**Comment by duracell80** [comment]
I did notice the split station in CRB was buggy. This was a user request to have 600 separate m3u files in a folder files if the tag contained 600 stations (crazy but whatever) it's defaulted to no because life is too short. Logos are also very tricky to deal with, everything else seemed to be ok.

**Comment by moodeaudio** [comment]
I tested briefly last night and I could not figure out what's happening under the covers by simply exploring the feature. There were also multiple times where the UI hung or timed out and displayed the "reconnect" screen. Since there is no documentation in this PR explaining how the feature works I'm not able to continue working with it.

Here's an example of a well documented feature. I'm able to get a clear understanding of what the feature and code is doing without using it or looking at any source code.
https://github.com/TheOldPresbyope/moode-radio-utils

**Comment by duracell80** [comment]
Yeah and that's fair. There's a bunch of python scripts actually doing some of the work. I can work on some more documentation.

The code is well commented as far as I can tell and I didn't touch any of the moode code aside from adding two buttons in lib-config.php. It's all self contained.

Some of the hanging issues could relate to file manipulation, do you have an example of where that happened?

**Comment by duracell80** [comment]
Just to at least give me a chance at helping you understand the rdo-config.php which I can re-provide in a new simpler pull request ... What questions do you have about the feature?

**Pull request closed without merging**
