### PR TITLE
CUE file support

### PR DESCRIPTION
**Pull request by Alberto-Bulpros**
Added CUE file parsing to retrieve the actual audio file(s) referred to inside the CUE sheet.

### CODE REVIEW

**Comment by moodeaudio** [comment]
Please email tim at moodeaudio dot org with a download link to a zip containing audio files that I use for testing.

**Comment by Alberto-Bulpros** [comment]
> Please email tim at moodeaudio dot org with a download link to a zip containing audio files that I use for testing.

Sorry I don't get you, Do you need some files for testing, or are you going to provide me with some?

**Comment by moodeaudio** [comment]
Yes, I need files for testing, preferably the same files that you used in your tests.

**Comment by Alberto-Bulpros** [comment]
> Yes, I need files for testing, preferably the same files that you used in your tests.

Well, I can add a couple of them. Of course I cannot give you my entire 1TB library of flacs+cue...

**Comment by moodeaudio** [comment]
lol, of course not. I just need a representative sample.

**Comment by Alberto-Bulpros** [comment]
> lol, of course not. I just need a representative sample.

OK then, see if I can manage it within 30 minutes / one hour from now... need to grab them from moOde, and upload them in my Google drive...

**Comment by Alberto-Bulpros** [comment]
Tim, you should have received the e-mail with the link.

Cheers, Al

**Comment by moodeaudio** [comment]
I downloaded the files, thanks!

Couple things before I start testing:

1. Delete the `.gitignore` and `package-lock.json` files from the PR otherwise they will overwrite the production files.
2. Revert the OSK commit and create a separate PR for it. We can't be mixing multiple different requests! Also since OSK are new files attach a license to the OSK project (in your repo) and include it in a program header for each of the files. Look in the moOde sources for examples.

**Comment by Alberto-Bulpros** [comment]
I'try my best on these.

Cheers, Al.
________________________________

**Comment by moodeaudio** [comment]
Actually I think deleting the two files is not the right way to remove them. Hang tight while I find out what the correct procedure is for fixing up the PR. It may take a while.

**Comment by moodeaudio** [comment]
Can't have node_modules in the PR!

Best way is for me to take the individual files that make up the cue enhancement and do a commit from my end. You will still get full credit in the commit.

**Pull request closed without merging**
