### PR TITLE
fix bug for create libcache.json null

### PR DESCRIPTION
**Pull request by lazybat**
Many Chinese songs or song directories have characters that are not UTF8, causing json_encode to fail.So libcache.json is empty.The library cannot be displayed.
Modifying the array passed in before json_encode solves this problem by removing the illegal characters.

### CODE REVIEW

**Comment by moodeaudio** [comment]
Hi @lazybat,

Thats a nice fix plus the other optimizations in the Lib routines. Do you feel that utf8rep() is universally applicable or should it be optional via a setting on System config?

I don't really use my Git repos for Pull requests or active development. I just push the entire moOde source tree after a release so other devs can view/fork the repo.

-Tim

**Comment by lazybat** [comment]
Hi, Tim
Thank you for your reply.
It is common practice to filter array content effectively before json_encode processing.However, it is more prudent to put this filter into the system Settings.
lazybat

**Comment by moodeaudio** [comment]
Hi @lazybat,

I ran across some of your nice modifications to the Browse and Library panels. Would you be interested in contributing the modifications to the moOde source Trunk? 

This would allow everyone to enjoy them along with the UTF8 fixes for Chinese character set.

-Tim

**Comment by lazybat** [comment]
Hello, Tim
The changes I made took a lot of time and were only used for friends who supported me.

**Comment by moodeaudio** [comment]
Hi @lazybat,

This is a friendly reminder that you are obligated under the terms of GPLv3, which moOde sources are licensed under, to provide anyone that requests them with your modified sources.

The following Taobao link shows a modified version of moOde 4.2 being publicly sold by "lazybat".  The screen shots are identical to what I ran across on other web searches
https://item.taobao.com/item.htm?spm=a230r.1.14.7.3f771071zMvybp&id=575101601540&ns=1&abbucket=2#detail

-Tim

**Comment by lazybat** [comment]
你好 Tim
        没错这个是我的链接，应朋友们的建议放的，为了能推广moode在中国diy hifi里的名气。迄今为止也只卖出一个，也还是我远程服务花了4小时帮助搞好的哦。当然开源协议要遵从，我会不定期更新我github里的代码。

Hello, Tim
Yes, this is my link, at the suggestion of my friends, in order to promote the popularity of moode in Chinese diy hifi.Only one has been sold so far, and I spent four hours on remote services to help out.Of course, open source protocols should be adhered to, and I will update my github code from time to time.

**Comment by moodeaudio** [comment]
@lazybat - You did not provide all the files for example indextpl.html is missing. 

Please comply with the GPL otherwise your distribution (image) of moOde audio player is illegal.

**Comment by lazybat** [comment]
hi Tim
           请注意你的态度，GPL说要分享代码，但是有提到立即分享吗？而且，我已经告诉你我会定期上传，就像你们一样，我fork下来的代码也都是4.1的，不是最新的4.2对吧？不要在这里威胁我！我已经删除了上传的镜像文件，如果你还能找到那也是别人的了！修改moode也存粹是喜欢它，希望它能更好对吧？你的语气好像我欠你什么一样？我欠你的吗？不欠！

Hi, Tim
Please note your attitude that GPL says to share code, but does it mention sharing immediately?Also, I've told you that I upload regularly, and like you, the code that comes down to my fork is 4.1, not the latest 4.2, right?Don't threaten me here!I have deleted the uploaded image file, if you can still find it is someone else's!Modifying moode also means liking it and hoping it will be better, right?You sound like I owe you something?Do I owe you anything?Don't owe!

**Comment by monkeypox** [comment]
You can modify moode for your own use and not have to share anything but when you distribute a modified version you are obligated by the license to make the source code available. Note that this requirement also applies to Tim, he has to make his source code available too, and that’s what allows your project to exist. You can keep your own image available as long as you meet the requirements of the GPL.

Steve / swizzle

**Comment by moodeaudio** [comment]
Hi @lazybat,

I've implemented this pull request in upcoming moOde 4.3 as a setting on the Customize screen. See attached screen shot.

-Tim
moode-r43e-utf8rep

**Pull request closed without merging**
