### PR TITLE
Allow artists/tracks from compilation albums to show up in tag view.

### PR DESCRIPTION
**Pull request by scripple**
Lists all artists from compilation albums in tag view artist list, and finds tracks on compilation albums when you select an artist.

### CODE REVIEW

**Comment by moodeaudio** [comment]
There are conflicts in this PR.

**Comment by scripple** [comment]
Yes, because it's against your r671prod tag, but github took the submit button away when I selected the tag.  Compare the results against the r671prod tag and there are no conflicts.

**Comment by moodeaudio** [comment]
It needs to be submitted against the Develop branch. The "prod" tags reflect the Master branch which is the production repo.

**Comment by scripple** [comment]
I have no running copy of your development branch, so I can't test it.  So I committed against what I tested.  You can look at the diff on github or your forum and merge into production.

**Comment by moodeaudio** [comment]
Will reopen when PR resubmitted against Develop branch with no conflicts.

**Pull request closed without merging**
