### PR TITLE
Amend setup.txt with some tips.

### PR DESCRIPTION
**Pull request by janiversen**
Added some tips, among other the tip on how to find a real radio stream.

I think these changes are relevant at user level.

### CODE REVIEW

**Comment by TheOldPresbyope** [comment]
There may be indirection or not. Depending on the source of the link, the endpoint may be a playable stream, it may be a .pls file, sometimes it may like the case explicitly shown here. Over the years we've seen lots of different links offered up by various users.

**Comment by janiversen** [comment]
Agreed, but this at least describes one way to get a proper stream....it solved a problem for me, and just maybe it can solve problems for others as well.

I have no problem adding extra text or changing the text. But I do think it is a nice hint on how to get the stream, so not writing anything just because it does not cover 100% seems strange to me.

Do you have a proposal on how to make the text to your liking ?

**Comment by moodeaudio** [comment]
It's useful information but it should be in the "FAQ and Guides" sub-forum and not in the Setup Guide.

The Setup Guide is meant to contain the steps needed to get a player operational out of the box plus some information on the command API.

**Comment by janiversen** [comment]
Ok I will move it, and add a reference to that sub forum. The problem I see is finding the information without knowing where it is,

**Comment by janiversen** [comment]
Content is moved, but the least we should have is a pointer to the forum, as newbies might not know it exist.

WDYT

**Comment by moodeaudio** [comment]
The challenge is that its human nature to "not read the manual" but in any case the Support and Developer pages at moodeaudio.org contain all the info and links needed to get to going.

**Comment by janiversen** [comment]
OK, I get the message!

I will close the PRs as they are not helpful to me, but could be to others. Sorry for disturbing. 

I am happily developing the feature I need, it turned out that what I need is a "special' multi room client, allowing me not only to use my earbuds, but also to use the speakers on my mac. I will post in the forum when it is ready to be used by others.

**Comment by moodeaudio** [comment]
The multi-room client sounds cool.

**Pull request closed without merging**
