### PR TITLE
Added 24-hour digital clock

### PR DESCRIPTION
**Pull request by fabitom**
24-hour format added to the digital clock of the screensaver

### CODE REVIEW

**Comment by moodeaudio** [comment]
Good idea but a simpler implementation would be to use the existing SQL param "scnsaver_mode" and add a new value "Digital clock (24 hour)" for example

```
... data-cmd="scnsaver-mode-sel"><span class="text">Digital clock</span></a></li>
... data-cmd="scnsaver-mode-sel"><span class="text">Digital clock (24 hour)</span></a></li>
```
```
function showSSClock() {
	switch (SESSION.json['scnsaver_mode']) {
		case 'Digital clock':
		case 'Digital clock (24 hour)':
                        var showAMPM = SESSION.json['scnsaver_mode'] == 'Digital clock (24 hour)' ? true : false;
			showSSDigitalClock(showAMPM);
			GLOBAL.ssClockIntervalID = setInterval(showSSDigitalClock, 1000);
			break;
```

**Comment by fabitom** [comment]
Yes, it may indeed be much simpler, simplified.

**Comment by moodeaudio** [comment]
Theres something odd happening in Git Desktop on my end when I try to merge the PR. It's saying the the develop branch is already up to date with the PR even though this is not the case.

If not too much trouble can you delete this PR and make a new one? Thanks.

**Comment by fabitom** [comment]
Yes, of course.

**Pull request closed without merging**
