### PR TITLE
Analog clock minimalistic

### PR DESCRIPTION
**Pull request by AlbertoNarduzzi**
Here it is (I had mistakenly merged my develop into the analog-clock, and not vice-versa...

### CODE REVIEW

**Comment by moodeaudio** [comment]
Couple things:

1. Does the position change for .ss-clock in panels.css affect the position of the Digital Clock?
2. CSS and JS file names should be hyphen delimited and lowercase -> analog-clock.css instead of analogClock.css
3. CSS class and id names should be hyphen delimited and lowercase -> analog-clock-hand { instead of .analogclock_hand {

It's up to you whether or not you want to do #2 and #3 because I'm in the process of refactoring the CSS anyway and so it's no problem for me to do these files after I merge the PR, prolly sometime next week.

**Comment by AlbertoNarduzzi** [comment]
I totally agree with the naming convention, I’ll try to fix it asap. for the position thing: no, my clock sets itself in the middle of its container, aka ss-clock.

**Comment by AlbertoNarduzzi** [comment]
Hi Tim,

I made all the relevant changes for the naming convention; anyway, I wanted
again, to merge analog-clock-minimal into my develop, and the contrary
happened (maybe I make some mistakes when resolving conflicts that lead the
changes to be saved in the wrong place...)

So, close/refuse the current PR, and later tonight, or tomorrow I'll make
another clean one.

Cheers, Al.

**Comment by moodeaudio** [comment]
Closed per request from submitter.

**Comment by AlbertoNarduzzi** [comment]
Hi Tim,

I made a new PR, Analog clock, minimalistic, name compliant (branch
Analog-clock-MkII)

one thing I'd like to point out is the following:
the analog clock can be configured (playerlib.js, line 658) like the
following:
showAnalogClock("ss-clock", ANALOGCLOCK_REFRESH_INTERVAL_SMOOTH, true);

"ss-clock" is the container, of course ANALOGCLOCK_REFRESH_INTERVAL_NORMAL
has the clock tick at 1Hz interval (e.g. like a quartz watch)
ANALOGCLOCK_REFRESH_INTERVAL_SMOOTH
ticks at 20Hz, resulting in the seconds-hand movement being smooth the last
parameter, here true, shows the seconds-hand, while false doesn't I do
prefer it configured this way, but feel free to change it as per your
preference (or eventually add an additional preference section for it, if
you feel like...) Cheers, Al.

**Comment by moodeaudio** [comment]
Hi Al,

It's always good to have options :-)

-Tim

**Pull request closed without merging**
