### PR TITLE
fixed donate URL

### PR DESCRIPTION
**Pull request by justinhorner**
I noticed the donate URL on the readme.md was not valid.  Found a valid URL on the moode audio forums and thought I would update the readme.

### CODE REVIEW

**Comment by moodeaudio** [comment]
Thanks :-)

**Comment by moodeaudio** [comment]
Thee was still a bit of breakage. The link below has solution
```
https://github.com/patharanordev/donate-in-git/blob/master/README.md
```

**Comment by justinhorner** [comment]
Thanks @moodeaudio.  Based on the code, it looks like you will have to fix it as the linked code calls for the account's email code.  Sorry for the erroneous PR.

**Comment by moodeaudio** [comment]
Already fixed :-)

**Pull request merged**
